name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  sqflite: ^2.0.0+3
  path_provider: ^2.1.3
  image_picker: ^1.1.2
  intl: ^0.17.0
  cupertino_icons: ^1.0.6
  table_calendar: ^3.0.0
  photo_manager: ^1.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/logo.png
    - assets/user_photo.jpg
    - assets/checklist.png
    - assets/photo.png
    - assets/calendar.png
    - assets/docx.png
    - assets/checklist_photo.png
    - assets/task_photo1.jpg
    - assets/task_photo2.jpg